server:
  #8030-8039
  port: 8030
  tomcat:
    min-spare-threads: 20
    max-threads: 1000
    max-connections: 1000
    accept-count: 1000
  connection-timeout: 5000

management:
  security:
    enabled: false

spring:
  main:
    banner-mode: "off"
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: test
    password: test
  datasource:
    asyncInit: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1/small_admin?serverTimezone=UTC&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
    userName: root
    password: 123456
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: -1
    filters: stat,wall,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

logging:
  config: classpath:config/log4j2.xml

jwt:
  expire: 86400
  pri-key:
    path: jwt/pri.key
  pub-key:
    path: jwt/pub.key
#阿里云OSS
aliyunOSS:
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAINGfHoGAG7x9K
  accessKeySecret: MAqsw2Ge0D8eeI1udOmTmUdT40XSTH
  bucketName: bucket20171023
#redis配置文件
redisson:
  url: https://github.com/itritritr/github-test/blob/master/config1/redisson.yml
#短信配置
sms:
  url: http://106.15.224.15:8088/sms.aspx
  userid: 440
  account: zhongcai1
  password: zhongcai123
  checkcontent: 0
  #每个手机号发送间隔(分钟)
  lit: 2
  templates: 
    val: 您的短信验证码是{0}。若非本人发送，请忽略此短信。本条短信免费。【湛江仲裁院】
