server:
  port: 8002
spring:
  main:
    banner-mode: "off"
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1/fengcms?serverTimezone=UTC&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true
    userName: fengcms
    password: fengcms
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: -1
    filters: stat,wall,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
logging:
  config: classpath:config/log4j2.xml