server:
  #8120-8129
  port: 8120
  tomcat:
    min-spare-threads: 20
    max-threads: 1000
    max-connections: 1000
    accept-count: 1000
  connection-timeout: 5000

management:
  security:
    enabled: false

logging:
  config: classpath:config/log4j2.xml

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 1000 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE

spring:
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

aliyunOSS:
  endpoint: http://oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAINGfHoGAG7x9K
  accessKeySecret: MAqsw2Ge0D8eeI1udOmTmUdT40XSTH
  bucketName: bucket20171023
